# Generated by Django 3.0.4 on 2020-03-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('exchange_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_account', models.IntegerField()),
                ('destiny_account', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('ci', models.IntegerField()),
                ('birthday', models.DateField()),
                ('direction', models.CharField(max_length=60)),
                ('creation_date', models.DateField(auto_now=True)),
                ('person_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.User')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.User')),
            ],
        ),
    ]
